definitions:
  const_application_api_controllers_feedback.Error:
    properties:
      message:
        type: string
    type: object
  const_application_api_controllers_ticket.Error:
    properties:
      message:
        type: string
    type: object
  const_application_api_controllers_transaction.Error:
    properties:
      message:
        type: string
    type: object
  const_application_api_controllers_user.Error:
    properties:
      message:
        type: string
    type: object
  const_core_services_transaction.Error:
    properties:
      message:
        type: string
    type: object
  controllers.Avaliacao:
    type: object
  controllers.Balance:
    properties:
      balance:
        type: number
    type: object
  controllers.Evento:
    type: object
  controllers.Ticket:
    type: object
  controllers.Transaction:
    properties:
      datadatransacao:
        type: string
      iddocomprador:
        type: integer
      iddoticket:
        type: integer
      precodevenda:
        type: number
      statusdatransacao:
        type: string
      tenantid:
        type: integer
      transacaoid:
        type: integer
    type: object
  controllers.User:
    properties:
      email:
        type: string
      nome:
        type: string
      tenantid:
        type: integer
      userid:
        type: integer
    type: object
  controllers.UserNotificationPreferences:
    type: object
  services.Transaction:
    properties:
      datadatransacao:
        type: string
      iddocomprador:
        type: integer
      iddoticket:
        type: integer
      precodevenda:
        type: number
      statusdatransacao:
        type: string
      tenantid:
        type: integer
      transacaoid:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/avaliacao:
    post:
      consumes:
      - application/json
      description: Create a new feedback
      parameters:
      - description: Avaliacao object
        in: body
        name: avaliacao
        required: true
        schema:
          $ref: '#/definitions/controllers.Avaliacao'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Avaliacao'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_feedback.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_feedback.Error'
      summary: Create a new feedback
      tags:
      - feedback
  /api/v1/event:
    get:
      consumes:
      - application/json
      description: Get all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Evento'
            type: array
      summary: Get all events
      tags:
      - event
    post:
      consumes:
      - application/json
      description: Create a new event
      parameters:
      - description: Evento object
        in: body
        name: ctx
        required: true
        schema:
          $ref: '#/definitions/controllers.Evento'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Evento'
      summary: Create a new event
      tags:
      - event
  /api/v1/event/{id}:
    delete:
      description: Delete event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: Delete event
      tags:
      - event
    get:
      consumes:
      - application/json
      description: Get event by ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Evento'
      summary: Get event by ID
      tags:
      - event
    put:
      consumes:
      - application/json
      description: Update event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: Event object
        in: body
        name: ctx
        required: true
        schema:
          $ref: '#/definitions/controllers.Evento'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Evento'
      summary: Update event
      tags:
      - event
  /api/v1/event/tenant/{tenantID}:
    get:
      consumes:
      - application/json
      description: Get events by tenant
      parameters:
      - description: Tenant ID
        in: path
        name: tenantID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Evento'
            type: array
      summary: Get events by tenant
      tags:
      - event
  /api/v1/events/{eventID}/tickets:
    get:
      consumes:
      - application/json
      description: Get available tickets by event
      parameters:
      - description: Event ID
        in: path
        name: eventID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Ticket'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
      summary: Get available tickets by event
      tags:
      - tickets
  /api/v1/tickets:
    post:
      consumes:
      - application/json
      description: Create a new ticket
      parameters:
      - description: Ticket object
        in: body
        name: ticket
        required: true
        schema:
          $ref: '#/definitions/controllers.Ticket'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Ticket'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
      summary: Create a new ticket
      tags:
      - tickets
  /api/v1/tickets/{ticketID}/use:
    put:
      consumes:
      - application/json
      description: Mark ticket as used
      parameters:
      - description: Ticket ID
        in: path
        name: ticketID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
      summary: Mark ticket as used
      tags:
      - tickets
  /api/v1/tickets/authenticate:
    post:
      consumes:
      - application/json
      description: Authenticate ticket
      parameters:
      - description: Ticket ID
        in: path
        name: ticketID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
      summary: Authenticate ticket
      tags:
      - tickets
  /api/v1/transaction:
    post:
      consumes:
      - application/json
      description: Purchase a ticket
      parameters:
      - description: Transaction object
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/controllers.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_transaction.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_transaction.Error'
      summary: Purchase a ticket
      tags:
      - transactions
  /api/v1/transaction/{id}/refund:
    put:
      consumes:
      - application/json
      description: Request refund
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_transaction.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_transaction.Error'
      summary: Request refund
      tags:
      - transactions
  /api/v1/transactions:
    post:
      consumes:
      - application/json
      description: Purchase a ticket
      parameters:
      - description: Transaction object
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/services.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/services.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_core_services_transaction.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_core_services_transaction.Error'
      summary: Purchase a ticket
      tags:
      - transactions
  /api/v1/transactions/{id}/refund:
    put:
      consumes:
      - application/json
      description: Request a refund
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_core_services_transaction.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_core_services_transaction.Error'
      summary: Request a refund
      tags:
      - transactions
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Create a new user
      tags:
      - users
  /api/v1/users/{id}:
    delete:
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Get user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Update user
      tags:
      - users
  /api/v1/users/{id}/balance:
    get:
      consumes:
      - application/json
      description: Get user balance
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Balance'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Get user balance
      tags:
      - users
  /api/v1/users/notification-preferences:
    post:
      consumes:
      - application/json
      description: Create user notification preferences
      parameters:
      - description: UserNotificationPreferences object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.UserNotificationPreferences'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.UserNotificationPreferences'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Create user notification preferences
      tags:
      - users
  /api/v1/users/notification-preferences/{id}:
    put:
      consumes:
      - application/json
      description: Update user notification preferences
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: UserNotificationPreferences object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.UserNotificationPreferences'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserNotificationPreferences'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_user.Error'
      summary: Update user notification preferences
      tags:
      - users
  /api/v1/users/tickets/{userID}:
    get:
      consumes:
      - application/json
      description: Get tickets by seller
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Ticket'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_ticket.Error'
      summary: Get tickets by seller
      tags:
      - tickets
  /api/v1/vendedor/{vendedorID}/avaliacao:
    get:
      consumes:
      - application/json
      description: Get feedbacks by seller
      parameters:
      - description: Seller ID
        in: path
        name: vendedorID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Avaliacao'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/const_application_api_controllers_feedback.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/const_application_api_controllers_feedback.Error'
      summary: Get feedbacks by seller
      tags:
      - feedback
swagger: "2.0"
