[psql]
  dbname = "postgres"
  host   = "postgres.cy3myhw5bsdp.us-east-1.rds.amazonaws.com"
  port   = 5432
  user   = "postgres"
  pass   = "xyV4YBeY8Qz2FuZ"
  sslmode = "disable"
  blacklist = ["goose_db_version"]