name: Deploy Lambda Function and Infrastructure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Initialize Go Module
        run: |
          go mod init csw24-grupoE-ticket4u-gin
          go mod tidy
        working-directory: ./src

      - name: Build Go project
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap
        working-directory: ./src
        
      - name: Create Zip file for Lambda function
        run: zip -j function.zip bootstrap
        working-directory: ./src
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:948675409837:function:csw24-grupoE-ticket4u-gin-lambda \
            --zip-file fileb://src/function.zip