name: Deploy Lambda Function and Infrastructure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Initialize Go Module
        run: |
          go mod init csw24-grupoE-ticket4u-gin
          go mod tidy

      - name: Build Go project
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap
        working-directory: ./src
        
      - name: Create Zip file for Lambda function
        run: zip -j function.zip bootstrap
        working-directory: ./src
        
      
      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}